// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"XdRs_Puzzle","status":true,"description":"拼图。","parameters":{"RandomBlankBlock":"ON","cpVal":"5","titleWord":"Family album","stepWord":"Steps:","cmd1":"Continue","cmd2":"Full picture","cmd3":"Exit","titleColor":"0,200,200","stepColor":"255,180,0","anmId":"48"}}
];
